import {
  BrickWall,
  Users,
  UserCheck,
  FileCheck,
  Settings,
  GitBranch,
  Play,
  Workflow,
  FileText,
  Calendar,
  AlertCircle,
  Database,
  Timer,
  Layers,
  CheckSquare,
  Network
} from "lucide-react";

export const menuItems = [
  {
    name: 'Workflow Engine Masters',
    icon: Workflow,
    route: '/workflow',
    features: [
      'Process Management',
      'Task Automation',
      'Instance Tracking',
      'Event Management',
      'SLA Monitoring',
    ],
    submenu: [
      {
        name: 'Contract',
        icon: FileText,
        route: '/workflow/contract',
        features: [
          'View All Contracts',
          'Search Contracts',
          'Add New Contract',
          'Edit Contract Details',
          'Delete Contract',
          'Contract Management',
        ],
      },
      {
        name: 'Contract Type',
        icon: FileText,
        route: '/workflow/contractType',
        features: [
          'View All Contract Types',
          'Search Contract Types',
          'Add New Contract Type',
          'Edit Contract Type Details',
          'Delete Contract Type',
          'Contract Type Management',
        ],
      },
      {
        name: 'Contract Status',
        icon: FileText,
        route: '/workflow/contractStatus',
        features: [
          'View All Contract Status',
          'Search Contract Status',
          'Add New Contract Status',
          'Edit Contract Status Details',
          'Delete Contract Status',
          'Contract Status Management',
        ],
      },
      {
        name: 'Contract Instance',
        icon: FileText,
        route: '/workflow/contractInstance',
        features: [
          'View All Contract Instance',
          'Search Contract Instance',
          'Add New Contract Instance',
          'Edit Contract Instance Details',
          'Delete Contract Instance',
          'Contract Instance Management',
        ],
      },
      {
        name: 'Cases Type',
        icon: FileCheck,
        route: '/workflow/caseType',
        features: [
          'View All Cases Types',
          'Search Cases Types',
          'Add New Case Type',
          'Edit Case Type Details',
          'Delete Case Type',
          'Case Type Management',
        ],
      },
      {
        name: 'Cases',
        icon: FileCheck,
        route: '/workflow/cases',
        features: [
          'View All Cases',
          'Search Cases',
          'Add New Case',
          'Edit Case Details',
          'Delete Case',
          'Case Status Management',
        ],
      },
      {
        name: 'Data Access Mode',
        icon: BrickWall,
        route: '/workflow/dataAccessMode',
        features: [
          'View All Data Access Modes',
          'Search Data Access Modes',
          'Add New Data Access Mode',
          'Edit Data Access Mode Details',
          'Delete Data Access Mode',
          'Data Access Mode Management',
        ],
      },
      
      {
        name: 'Process Type',
        icon: Database,
        route: '/workflow/processType',
        features: [
          'View All Process Types',
          'Search Process Types',
          'Add New Process Type',
          'Edit Process Type Details',
          'Delete Process Type',
          'Process Type Management',
        ],
      },
      {
        name: 'Process',
        icon: Database,
        route: '/workflow/process',
        features: [
          'View All Processes',
          'Search Processes',
          'Add New Process',
          'Edit Process Details',
          'Delete Process',
          'Process Configuration',
        ],
      },
      {
        name: 'Workflow Type',
        icon: Workflow,
        route: '/workflow/workflowType',
        features: [
          'View All Workflow Types',
          'Search Workflow Types',
          'Add New Workflow Type',
          'Edit Workflow Type Details',
          'Delete Workflow Type',
          'Workflow Type Management',
        ],
      },
      {
        name: 'Workflow',
        icon: Workflow,
        route: '/workflow/workflow',
        features: [
          'View All Workflows',
          'Search Workflows',
          'Add New Workflow',
          'Edit Workflow Details',
          'Delete Workflow',
          'Workflow Design',
        ],
      },
      {
        name: 'Actor',
        icon: Users,
        route: '/workflow/actor',
        features: [
          'View All Actors',
          'Search Actors',
          'Add New Actor',
          'Edit Actor Details',
          'Delete Actor',
          'Assign Roles',
        ],
      },


      {
        name: 'SLA',
        icon: Timer,
        route: '/workflow/sla',
        features: [
          'View All SLAs',
          'Search SLAs',
          'Add New SLA',
          'Edit SLA Details',
          'Delete SLA',
          'SLA Monitoring',
        ],
      },
      {
        name: 'Stage Type',
        icon: Layers,
        route: '/workflow/stageType',
        features: [
          'View All Stage Types',
          'Search Stage Types',
          'Add New Stage Type',
          'Edit Stage Type Details',
          'Delete Stage Type',
          'Stage Type Management',
        ],
      },
      {
        name: 'Stage',
        icon: Layers,
        route: '/workflow/stage',
        features: [
          'View All Stages',
          'Search Stages',
          'Add New Stage',
          'Edit Stage Details',
          'Delete Stage',
          'Stage Configuration',
        ],
      },
      {
        name: 'Task Type',
        icon: CheckSquare,
        route: '/workflow/taskType',
        features: [
          'View All Task Types',
          'Search Task Types',
          'Add New Task Type',
          'Edit Task Type Details',
          'Delete Task Type',
          'Task Type Management',
        ],
      },
      {
        name: 'Task Mutual Group',
        icon: CheckSquare,
        route: '/workflow/taskMutualGroup',
        features: [
          'View All Task Mutual Groups',
          'Search Task Mutual Groups',
          'Add New Task Mutual Group',
          'Edit Task Mutual Group Details',
          'Delete Task Mutual Group',
          'Task Mutual Group Management',
        ],
      },
      {
        name: 'Task',
        icon: CheckSquare,
        route: '/workflow/task',
        features: [
          'View All Tasks',
          'Search Tasks',
          'Add New Task',
          'Edit Task Details',
          'Delete Task',
          'Task Assignment',
        ],
      },


      {
        name: 'Actor Group',
        icon: UserCheck,
        route: '/workflow/actor-group',
        features: [
          'View All Actor Groups',
          'Search Actor Groups',
          'Add New Actor Group',
          'Edit Actor Group Details',
          'Delete Actor Group',
          'Manage Group Members',
        ],
      },

      {
        name: 'Case Instance',
        icon: FileText,
        route: '/workflow/case-instance',
        features: [
          'View All Case Instances',
          'Search Case Instances',
          'Add New Case Instance',
          'Edit Case Instance Details',
          'Delete Case Instance',
          'Instance Status Tracking',
        ],
      },
      // {
      //   name: 'Case Process',
      //   icon: GitBranch,
      //   route: '/workflow/case-process',
      //   features: [
      //     'View All Case Processes',
      //     'Search Case Processes',
      //     'Add New Case Process',
      //     'Edit Case Process Details',
      //     'Delete Case Process',
      //     'Process Flow Management',
      //   ],
      // },
      {
        name: 'Case Process Instance',
        icon: Play,
        route: '/workflow/case-process-instance',
        features: [
          'View All Process Instances',
          'Search Process Instances',
          'Add New Process Instance',
          'Edit Process Instance Details',
          'Delete Process Instance',
          'Instance Monitoring',
        ],
      },
      {
        name: 'Case Process Workflow',
        icon: Network,
        route: '/workflow/case-process-workflow',
        features: [
          'View All Process Workflows',
          'Search Process Workflows',
          'Add New Process Workflow',
          'Edit Process Workflow Details',
          'Delete Process Workflow',
          'Workflow Design',
        ],
      },
      {
        name: 'Case Process Workflow Instance',
        icon: Settings,
        route: '/workflow/case-process-workflow-instance',
        features: [
          'View All Workflow Instances',
          'Search Workflow Instances',
          'Add New Workflow Instance',
          'Edit Workflow Instance Details',
          'Delete Workflow Instance',
          'Instance Execution Tracking',
        ],
      },
      {
        name: 'Event Type',
        icon: Calendar,
        route: '/workflow/eventType',
        features: [
          'View All Event Types',
          'Search Event Types',
          'Add New Event Type',
          'Edit Event Type Details',
          'Delete Event Type',
          'Event Type Management',
        ],
      },

      {
        name: 'Event',
        icon: Calendar,
        route: '/workflow/event',
        features: [
          'View All Events',
          'Search Events',
          'Add New Event',
          'Edit Event Details',
          'Delete Event',
          'Event Scheduling',
        ],
      },
      {
        name: 'Instance Status',
        icon: AlertCircle,
        route: '/workflow/instance-status',
        features: [
          'View All Instance Status',
          'Search Instance Status',
          'Add New Instance Status',
          'Edit Instance Status Details',
          'Delete Instance Status',
          'Status Management',
        ],
      },

      {
        name: 'Test API',
        icon: Database,
        route: '/test',
        features: [
          'Test API Connections',
          'Debug API Calls',
          'View API Response',
        ],
      },

    ],
  },
  {
    name: 'Create Workflow',
    icon: Network,
    route: '/workflow/builder',
    features: [
      'Visual Workflow Designer',
      'Drag & Drop Interface',
      'Process Flow Creation',
      'Contract Management',
      'Case Mapping',
      'Task Assignment',
      'Stage Configuration'
    ],
  },
]